# Generated by Django 3.2.4 on 2021-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='billing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.CharField(blank=True, default=0, max_length=12, null=True, unique=True, verbose_name='ИНН'),
        ),
    ]
