# Generated by Django 3.2.4 on 2021-06-27 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='billing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.CharField(blank=True, default=0, max_length=12, null=True, unique=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
